### ISSUE TITLE
Hibernate session issues

### ISSUE THREAD

**Issue by davecramer** [budjb/grails-rabbitmq-native#40]
With the latest version I am getting:
an assertion failure occured (this may indicate a bug in Hibernate, but is more likely due to unsafe use of the session): org.hibernate.AssertionFailure: null id in ca.xxxxxh.FareCountByVendor entry (don't flush the Session after an exception occurs)

Previous 1.0.2 with exactly the same code does not exhibit this problem.

Suggestions ?

**Comment by budjb** [comment]
I'm working on an example to reproduce the error you're seeing.  I'll update when I have more info.

**Comment by budjb** [comment]
I've managed to create an example where I can force an error in the hibernate session (which will output the error message in the original issue post), but I'm seeing that the consumer code handles it properly.

I can't seem to reproduce your issue, probably because I don't have any insight into the sequence of events that leads to the issue.  Is it possible to provide a code example that mimics what your code is doing?

**Comment by davecramer** [comment]
Hi Bud,

I'll see what I can do, but I have a working solution so this isn't an
urgent problem for me.

Dave Cramer

**Comment by budjb** [comment]
Thanks Dave.  If there is an issue here I'd love to get it fixed, so any help you can provide would be appreciated.

**Comment by budjb** [comment]
I'm going to close this issue since there's not been a lot of progress on it.  If you run into this again, please feel free to reopen it.
