### ISSUE TITLE
RabbitMQ Native Plugin using?

### ISSUE THREAD

**Issue by dudulive** [budjb/grails-rabbitmq-native#43]
I'm having problems in the exchange of messages between two applications using RabbitMQ Native Plugin, messages are exchanged but when I try to view the message body is null in view, to the following documentation but TA does not help: link: http: // budjb .github.io / grails-RabbitMQ-native / doc / manual / guide / quickstart.html
below the codes:
application produces messages.

package com.example

import com.budjb.rabbitmq.RabbitMessageBuilder

class ProdutorController {

    def index() {

        render new RabbitMessageBuilder().send {
            routingKey = "atendimento_ti"
            timeout = 0
            body = "Produziu-1"
        }
    }

}

consumer messaging application:
import com.budjb.rabbitmq.MessageContext

class ConsumidorConsumer {
    /**
     * Consumer configuration.
     */
    static rabbitConfig = [
            queue: "atendimento_ti"
    ]

    /**
     * Handle an incoming RabbitMQ message.
     *
     * @param body    The converted body of the incoming message.
     * @param context Properties of the incoming message.
     * @return
     */
    def handleMessage(def body, MessageContext context) {
        println body
        return body
    }
}

import com.budjb.rabbitmq.RabbitMessageBuilder

class ConsumidorController {

    def index() {
        render new RabbitMessageBuilder().getBody();
    }
}

**Comment by budjb** [comment]
Are you trying to set up an RPC-style request?  You are returning the body from the consumer, which leads me to believe you are.

Since you used the send() method in the initial message builder, no response is expected, so your return is effectively ignored.

The index action near the end of your post will always return null.  The message builder only builds a request and either sends it, or sends it and waits for a response.  Body is defaulted to null, and since you did not send() nor rpc(), and never set body, body will be null.  Here's what I think you're trying to do:
```
package com.example

import com.budjb.rabbitmq.RabbitMessageBuilder

class ProdutorController {
    def index() {
        render new RabbitMessageBuilder().rpc {
            routingKey = "atendimento_ti"
            timeout = 0
            body = "Produziu-1"
        }
    }
}
```
package com.example

import com.budjb.rabbitmq.MessageContext

class ConsumidorConsumer {
    /**
     * Consumer configuration.
     */
    static rabbitConfig = [
        queue: "atendimento_ti"
    ]

    /**
     * Handle an incoming RabbitMQ message.
     *
     * @param body    The converted body of the incoming message.
     * @param context Properties of the incoming message.
     * @return
     */
    def handleMessage(def body, MessageContext context) {
        println body
        return body
    }
}
```
Does this make sense?

**Comment by dudulive** [comment]
I did as you said the message is being sent by ProdutorController and ConsumidorConsumer this printed the body on the island, however what I need is to print the body (message) from ConsumidorConsumer in the browser using a ConsumidorController, noting that ProdutorController is an application and ConsumidorConsumer , ConsumidorController in another application if you have some idea now thanks.

**Comment by dudulive** [comment]
To illustrate'm trying to make the application Sending messages to the application B and the application B print in the received message browser.
Thanks in advance.

**Comment by dudulive** [comment]
I need face much has already two days it helps me!

**Comment by budjb** [comment]
What you're trying to do requires a little more effort.  Since a web request is stateless, there's no way for the browser to render incoming messages without more work on the backend.  As a simple solution, I'd implement some kind of database table that the message consumer uses to store messages in until the next web request.  During that web request, I'd pull all the new message entries, and then either delete them or mark them read, and then render those messages out to the webpage.

In the HTML frontend, you can write a little javascript to automatically refresh the page on some interval.

**Comment by dudulive** [comment]
I have the following problem the consumer is outside the web context and put it in that context.
The cast error:
2015-02-06 14:52:11,389 [pool-7-thread-2] ERROR rabbitmq.RabbitConsumer  - unhandled exception java.lang.IllegalStateException caught in RabbitMQ message handler for consumer Atendimento_tiConsumer
Message: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet/DispatcherPortlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
    Line | Method
->>  139 | internacionalize                 in utils.Aplicacao
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    371 | enviarEmailAtendentimentoFechado in atendimento.Atendimento_tiService$$EP3WxTd4
|     22 | handleMessage . . . . . . . . .  in atendimento.Atendimento_tiConsumer
|    365 | processMessage                   in com.budjb.rabbitmq.RabbitConsumer
|    293 | handleDelivery . . . . . . . . . in     ''
|    140 | run                              in com.rabbitmq.client.impl.ConsumerDispatcher$5
|     85 | run . . . . . . . . . . . . . .  in com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable
|   1145 | runWorker                        in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . . . . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
^    744 | run                              in java.lang.Thread
