### ISSUE TITLE
Can I define queues in plugins

### ISSUE THREAD

**Issue by liling** [budjb/grails-rabbitmq-native#61]
We have a project which use this great plugin.

I have a problem. We have create a log of small plugins which provide optional functions and some of them use Rabbit MQ. I want to define connections in project level and queues in plugin level.

But after I read the documents, I found I can only define queues in project config.groovy and the plugin can't define their own queues. Is this true?

**Comment by budjb** [comment]
I never wrote in support for this use case.  If this is a big enough problem, I'll see about adding something.

**Comment by liling** [comment]
I think there are two use cases.
1. We have write a internal plugin to manage user information, which is used in many small apps for one organization. When user update information such as email or mobile I want all apps update immediately. And I think the exchange and queue config should be defined in plugin not all apps.
2. We have a project which compose of many small project plugins. Every plugin provide different functions, and they all define their own exchange or queue. If we deploy the project for different organization, and they may choose some of the plugins. I need to define the queue and exchange in plugins in order to prevent change project config every time.

The problem is we have move some functions from project to plugins, so define queue and exchange in plugin is needed.

**Comment by budjb** [comment]
I'm working on making a small change to the queue builder so that plugins can pass their own configuration closures, but until that's released, can you write queue building logic into your own plugin right now.

Using the `connectionManager` bean, you can get the rabbitmq connection object for the connection you need to configure queues for, create a channel, and define exchanges, queues, and bindings through the rabbitmq java client itself.

I'd make sure your plugin runs after the rabbitmq-native plugin, and in the `doWithApplicationContext` closure, do whatever queue configuration you need done.

I'll update when the closure-based configuration change is released.
